
<script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.19.1/TweenMax.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/ScrollMagic.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/debug.addIndicators.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.5/plugins/animation.gsap.min.js"></script>

<script>

    var controller=new ScrollMagic.Controller;new ScrollMagic.Scene({triggerElement:".secondary-nav-trigger"}).setClassToggle(".ipf-secondary-nav","move_in").addIndicators({name:"1 - add a class"}).removeIndicators().addTo(controller);var controllerParalax=new ScrollMagic.Controller({globalSceneOptions:{triggerHook:"onEnter",duration:"200%"}}),home_tween=(new TimelineMax).add([TweenMax.fromTo(".web-deco-large",1,{bottom:80},{bottom:300,ease:Linear.easeNone}),TweenMax.fromTo(".web-deco-small",1,{bottom:130},{bottom:90,ease:Linear.easeNone})]);new ScrollMagic.Scene({triggerElement:".ipf-mobile-service"}).setTween(home_tween).removeIndicators().addTo(controllerParalax);var dm_tween=(new TimelineMax).add([TweenMax.fromTo(".facebook-icon",1,{top:0},{top:150,ease:Linear.easeNone}),TweenMax.fromTo(".twitter-icon",1,{top:300},{top:150,ease:Linear.easeNone}),TweenMax.fromTo(".google-icon",1,{top:130},{top:150,ease:Linear.easeNone}),TweenMax.fromTo(".insta-icon",1,{top:0},{top:150,ease:Linear.easeNone}),TweenMax.fromTo(".email-icon",1,{top:200},{top:150,ease:Linear.easeNone})]);new ScrollMagic.Scene({triggerElement:".ipf-digital-service"}).setTween(dm_tween).removeIndicators().addTo(controllerParalax);var clients_tween=(new TimelineMax).add([TweenMax.fromTo(".client-large-deco",1,{top:130},{top:400,ease:Linear.easeNone}),TweenMax.fromTo(".client-small-deco",1,{bottom:130},{bottom:400,ease:Linear.easeNone})]);new ScrollMagic.Scene({triggerElement:".ipf-clients"}).setTween(clients_tween).removeIndicators().addTo(controllerParalax);var footer_tween=(new TimelineMax).add([TweenMax.fromTo(".footer-large-deco",1,{top:100},{top:1e3,ease:Linear.easeNone})]);new ScrollMagic.Scene({triggerElement:".ipf-footer"}).setTween(footer_tween).removeIndicators().addTo(controllerParalax);var approach_tween=(new TimelineMax).add([TweenMax.fromTo(".approach-text",1,{top:500},{top:300,ease:Linear.easeNone})]);new ScrollMagic.Scene({triggerElement:".ipf-approach h1"}).setTween(approach_tween).removeIndicators().addTo(controllerParalax),new ScrollMagic.Scene({triggerElement:".secondary-nav-trigger",reverse:!1}).setClassToggle(".values","animated").addIndicators({name:"1 - add a class"}).removeIndicators(),new ScrollMagic.Scene({triggerElement:".ipf-about-services",reverse:!1}).setClassToggle(".services div","animated").addIndicators({name:"Service trigger"}).removeIndicators().addTo(controller);


</script>